# Generated by Django 5.1.7 on 2025-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rationcard',
            name='issued_date',
        ),
        migrations.AlterField(
            model_name='rationcard',
            name='card_type',
            field=models.CharField(max_length=50),
        ),
    ]
