# Generated by Django 5.1.7 on 2025-03-14 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('ration_type', models.CharField(choices=[('APL', 'Above Poverty Line'), ('BPL', 'Below Poverty Line'), ('AAY', 'Antyodaya Anna Yojana')], max_length=50)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
        ),
    ]
